apiVersion: v1
kind: Service
metadata:
  name: ${name}
  namespace: ${namespace}
  labels:
    name: mysql
    version: ${version}
    type: database
spec:
  selector:
    name: mysql
    version: ${version}
    type: database
  ports:
    - port: 3306
  type: NodePort