server:
  port: 10012

spring:
  application:
    name: LOGIN
  security:
    oauth2:
      client:
        registration:
          centcas:
            client-id: 100001
            client-secret: 100001abcdefg
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:10012/login/oauth2/code/centcas
            redirect-uri-template: http://localhost:10012/login/oauth2/code/centcas
            provider: centcas
            scope: read:user
        provider:
          centcas:
            authorization-uri: http://codefanpc:8088/cas/oauth2.0/authorize
            token-uri: http://codefanpc:8088/cas/oauth2.0/accessToken
            user-info-uri: http://codefanpc:8088/cas/oauth2.0/profile
resource-uri: https://api.github.com/user/repos
